# This file should contain all the record creation needed to seed the database with its default values.# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).## Examples:##   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])#   Character.create(name: 'Luke', movie: movies.first) 
Portfolio.create(title: 'Online Presentation website (Padlet.com)', overview: 'From your hobby to your career, your class notes to your final exam, your mood board to your runway show,  padlet help you organize your life.You can build own presentation and templates with pictures, articles with attachments and can share that with other members.It is also integrating payment features for more professional use.Here I mainly did canvas part.', 
  period: "2007-2008", skillset: ["React", "Node"], img: "portfolio_img/padlet.png")
Portfolio.create(title: 'delivery service website (http://en.ginzadelivery.ru/)', overview: 'Ginza is one of food delivery service in Russia and I have participated in building web application for that service. Users can browse the website and can request delivery.This site includes online payment integration system.Here I did mainly front end part with 2 members and other 2 members did backend job.', 
  period: "2008-2009", skillset: ["React", "Node"], img: "portfolio_img/ginzadelivery.png")
Portfolio.create(title: 'Real estate website (labelfiorita-verona.com)', overview: 'Real estate site that I built. It is presenting mainly pictures and location of the real estates .Also you can browse and book the rooms and swimming pools when you are going to travel there.For booking it is integrating EUR payment system.', 
  period: "2009-2010", skillset: ["React", "Node"], img: "portfolio_img/real_estate.png")
Portfolio.create(title: 'CRM website (capsulecrm.com)', overview: 'It is online CRM for individuals, small businesses and sales teams wanting a simple, effective and affordable solution. It helps businessmans managing contacts and their history.  It contains all the features that general CRMs have and design is little special.', 
  period: "2011-2012", skillset: ["React", "Node"], img: "portfolio_img/CRM.png")
Portfolio.create(title: 'Video Chatting website (https://www.gruveo.com)', overview: 'This is online video and audio streaming website without signup.Once you create a room for video & audio call with high quality and others and connect that room with name.Names can be shared with other communication tools.', 
  period: "2011-2012", skillset: ["React", "Node"], img: "portfolio_img/video_call.png")
Portfolio.create(title: 'Signing Website (esigngenie.com)', overview: "This digital signature web application's purpose was built for online signature.Nowadays, lots of people are working online and also signing is also done online. The basic structure of this application is like this.First import PDF or doc file from local engine and make box for signing.And email is send to the end parties that have to sign.After signature is done that documentation is available on the database and also available as PDF file that is downloadable.So it's really useful for start contract between parties.This app's back end was built using Node and Express.Front end pages were built using react and bootstrap.I have built MVP of this web application and it was really nice experience understanding about signature.",
  period: "2012-2014", skillset: ["React", "Node"], img: "portfolio_img/digital_sign.png")
Portfolio.create(title: 'Cryptocurrency website (zozocoins.com)', overview: 'Zozocoin is one of cryptocurrency that was customized from dash coin.   I was involved in team of 3 guys. One was designer and two were developers.   I have customized protocols and UIs for new coin with the other developer and built core executive and apps for unix, osx, win64, win_32, linux and built masternodes for the ICO process. At the end of work, I have developed websites of new coin. ', 
  period: "2014-2015", skillset: ["React", "Node"], img: "portfolio_img/zozocoin.png") 
Portfolio.create(title: 'Personal Website (3villagechiropractic.com, bodyspinewellness.com)', overview: 'This is personal website of Dr. Brian Roth, he is massage expert and own a small hospital.It mainly contains with articles he wanted to show and on admin side, it allows adding more articles and pictures with custom styles.You can meet the members of that hospital with this sites and can personally contact them.', 
  period: "2015-2017", skillset: ["React", "Node"], img: "portfolio_img/personal_website.png")